version: '3'
services:
  web:
    image: momscraper-web
    build: ./web
    depends_on:
        - api
    ports:
      - "8000:80"
    volumes:
      - ./web/dist:/var/www
  api:
    image: momscraper-api
    build: ./api
