version: '3'
services:
  web:
    restart: always
    networks:
      - nginx_shared-network
  api:
    restart: always
    networks:
      - nginx_shared-network

networks:
  nginx_shared-network:
    external: true
